server:
    port: 8081

application:
    bourse:
        baseUri: http://localhost:8090/

spring:
    datasource:
        url: jdbc:h2:./.db/springboot-h2/courtage-db
        username: sa
        password: password
        driverClassName: org.h2.Driver
    jpa:
        properties:
            hibernate:
                show_sql: false
                format_sql: false
                use_sql_comments: false
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update

    h2:
        # Mise Ã  disposition d'une IHM pour visualiser le contenu de la BDD H2
        console:
            enabled: true
            path: /h2-ui
